export default [
  {
    date: '2021-01-03',
    type: 'expense',
    category: 'drinks',
    account: 'myvisa1',
    amount: '230',
    description: 'Vine',
  },
  {
    date: '2021-01-04',
    type: 'expense',
    category: 'graceries',
    account: 'myvisa1',
    amount: '130',
    description: 'Milk, bread',
  },
  {
    date: '2019-01-05',
    type: 'expense',
    category: 'travel',
    account: 'myvisa1',
    amount: '60000',
    description: '',
  },
  {
    date: '2020-07-07',
    type: 'expense',
    category: 'joy',
    account: 'myvisa1',
    amount: '3000',
    description: '',
  },
  {
    date: '2021-01-03',
    type: 'expense',
    category: 'transport',
    account: 'myvisa1',
    amount: '40',
    description: 'Bus',
  },
  {
    date: '2020-12-12',
    type: 'income',
    category: 'salary',
    account: 'myvisa1',
    amount: '20000',
    description: '',
  },
  {
    date: '2020-12-12',
    type: 'income',
    category: 'casino',
    account: 'myvisa1',
    amount: '10000',
    description: '',
  },
  {
    date: '2020-01-05',
    type: 'income',
    category: 'freelance',
    account: 'myvisa1',
    amount: '3000',
    description: '',
  },
  {
    date: '2020-11-10',
    type: 'expense',
    category: 'beauty',
    account: 'myvisa1',
    amount: '1000',
    description: 'Haircut',
  },
  {
    date: '2021-01-01',
    type: 'income',
    category: 'salary',
    account: 'myvisa1',
    amount: '30000',
    description: '',
  },
  {
    date: '2020-01-08',
    type: 'expense',
    category: 'transport',
    account: 'myvisa1',
    amount: '345',
    description: 'taxi',
  },
  {
    date: '2021-01-08',
    type: 'expense',
    category: 'transport',
    account: 'myvisa1',
    amount: '45',
    description: 'bus',
  },
  {
    date: '2020-11-01',
    type: 'income',
    category: 'freelance',
    account: 'myvisa1',
    amount: '10000',
    description: '',
  },
  {
    date: '2020-10-01',
    type: 'income',
    category: 'freelance',
    account: 'myvisa1',
    amount: '1500',
    description: '',
  },
  {
    date: '2021-09-01',
    type: 'income',
    category: 'gift',
    account: 'myvisa1',
    amount: '3000',
    description: '',
  },
  {
    date: '2020-12-12',
    type: 'expense',
    category: 'healthcare',
    account: 'myvisa1',
    amount: '117',
    description: 'medicine',
  },
  {
    date: '2021-01-05',
    type: 'expense',
    category: 'drinks',
    account: 'myvisa1',
    amount: '100',
    description: 'Bear',
  },
  {
    date: '2021-07-12',
    type: 'expense',
    category: 'gifts',
    account: 'myvisa1',
    amount: '500',
    description: '',
  },
  {
    date: '2020-01-21',
    type: 'expense',
    category: 'graceries',
    account: 'myvisa1',
    amount: '1500',
    description: 'meal',
  },
];
